apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookie-deployment
  labels:
    app: hlbookie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hlbookie
  template:
    metadata:
      labels:
        app: hlbookie
    spec:
      containers:
      - name: hlbookie
        image: halbard/bookie-flask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password